import { Montserrat } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Navbar from "./components/navber";
import Footer from "./components/footer";
import CallNowButton from "./components/CallNowButton";
import QuoteButton from "./components/QuoteButton";
import Purchase from "./components/Purchase";
import BackToTop from "./components/BackToTop";
import { SpeedInsights } from "@vercel/speed-insights/next"

// Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"], // add weights you need
});

// Geist fonts (your existing ones)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Making Moves Matter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-US" data-arp>
      <head>
        <link
          rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.7.2/css/all.css"
        />
      </head>
      <body
        className={`${montserrat.variable}antialiased`}
      >
        <Navbar />
        {children}
        <SpeedInsights />
        <Footer />
        <CallNowButton />
        <QuoteButton />
        <Purchase />
        <BackToTop />
      </body>
    </html>
  );
}
